{{- if not .Values.secrets.existingSecret }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "semaphoreui.fullname" . }}-general
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphoreui.labels" . | nindent 4 }}
{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

type: Opaque
data:
  {{- $generalSecretName := printf "%s-general" (include "semaphoreui.fullname" .) }}
  {{- $generalSecretObj := (lookup "v1" "Secret" .Release.Namespace $generalSecretName) | default dict }}
  {{- $generalSecretData := (get $generalSecretObj "data") | default dict }}
  {{- $cookieHash := (get $generalSecretData .Values.secrets.cookieHashKey) | default (randAlphaNum 32 | b64enc | b64enc) }}
  {{ .Values.secrets.cookieHashKey }}: {{ .Values.secrets.cookieHash | default ($cookieHash) }}
  {{- $cookieEncryptionKey := (get $generalSecretData .Values.secrets.cookieEncryptionKey) | default (randAlphaNum 32 | b64enc | b64enc) }}
  {{ .Values.secrets.cookieEncryptionKey }}: {{ .Values.secrets.cookieEncryption | default ($cookieEncryptionKey) }}
  {{- $accesskeyEncryptionKey := (get $generalSecretData .Values.secrets.accesskeyEncryptionKey) | default (randAlphaNum 32 | b64enc | b64enc) }}
  {{ .Values.secrets.accesskeyEncryptionKey }}: {{ .Values.secrets.accesskeyEncryption | default ($accesskeyEncryptionKey) }}
{{- end }}
