{{- if not .Values.runner.existingSecret }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "semaphoreRunner.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphoreRunner.labels" . | nindent 4 }}
{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

type: Opaque
data:
  {{- $secretName := printf "%s-token" (include "semaphoreRunner.fullname" .) }}
  {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $existingData := (get $existing "data") | default dict }}
  {{- if .Values.runner.registrationToken }}
  {{ .Values.runner.registrationTokenKey }}: {{ .Values.runner.registrationToken | b64enc }}
  {{- else if (get $existingData .Values.runner.registrationTokenKey) }}
  {{ .Values.runner.registrationTokenKey }}: {{ get $existingData .Values.runner.registrationTokenKey }}
  {{- end }}
  {{- if .Values.runner.apiToken }}
  {{ .Values.runner.apiTokenKey }}: {{ .Values.runner.apiToken | b64enc }}
  {{- else if (get $existingData .Values.runner.apiTokenKey) }}
  {{ .Values.runner.apiTokenKey }}: {{ get $existingData .Values.runner.apiTokenKey }}
  {{- end }}
{{- end }}
