{{- if not .Values.runner.existingKeySecret }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "semaphoreRunner.fullname" . }}-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphoreRunner.labels" . | nindent 4 }}
{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

type: Opaque
data:
  {{- $secretName := printf "%s-key" (include "semaphoreRunner.fullname" .) }}
  {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $existingData := (get $existing "data") | default dict }}
  {{- $existingKey := get $existingData .Values.runner.privateKeyKey }}
  {{- if .Values.runner.privateKey }}
  {{ .Values.runner.privateKeyKey }}: {{ .Values.runner.privateKey | b64enc }}
  {{- else if $existingKey }}
  {{ .Values.runner.privateKeyKey }}: {{ $existingKey }}
  {{- else }}
  {{- $generated := genPrivateKey "ed25519" }}
  {{ .Values.runner.privateKeyKey }}: {{ $generated | b64enc }}
  {{- end }}
{{- end }}
