{{- if and (not .Values.telegram.existingSecret) (.Values.telegram.alert) }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "semaphoreui.fullname" . }}-telegram
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphoreui.labels" . | nindent 4 }}
{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

type: Opaque
data:
  {{ .Values.telegram.chatKey }}: {{ .Values.telegram.chat | b64enc }}
  {{ .Values.telegram.tokenKey }}: {{ .Values.telegram.token | b64enc }}
{{- end }}
