---
name: helmdocs

"on":
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  helmdocs:
    runs-on: ubuntu-latest
    if: github.repository == 'semaphoreui/charts'

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Update readme
        id: docs
        uses: docker://jnorwood/helm-docs:v1.14.2
        with:
          entrypoint: helm-docs

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Denis Gukov
          author_email: denguk@gmail.com
          add: stable/
          message: "docs: automated readme update [skip ci]"
          push: true
          commit: --signoff

...
