---
name: release

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'semaphoreui/semaphore-charts'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup helm
        uses: azure/setup-helm@v4

      - name: Configure Git
        run: |
          git config user.name "Denis Gukov"
          git config user.email "denguk@gmail.com"

      - name: Update readme
        uses: docker://jnorwood/helm-docs:v1.14.2
        with:
          entrypoint: helm-docs

      - name: Write secring
        run: |
          echo -n "${{ secrets.GPG_KEY }}" \
            | base64 --decode \
            > /tmp/secring.gpg

      # - name: Write passphrase
      #   run: |
      #     echo -n "${{ secrets.GPG_PASS }}" \
      #       > passphrase

      - name: Run releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GH_TOKEN }}
          CR_KEYRING: /tmp/secring.gpg
          # CR_PASSPHRASE_FILE: passphrase
        with:
          config: cr.yaml
          charts_dir: stable

      - name: Push charts
        run: |
          echo "${{ secrets.GH_TOKEN }}" | helm registry login --username fiftin --password-stdin ghcr.io

          for pkg in .cr-release-packages/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi

            echo "Pushing $pkg..."
            helm push "$pkg" "oci://ghcr.io/$GITHUB_REPOSITORY_OWNER/charts"
          done

      - name: Remove secrets
        if: always()
        run: |
          rm -f /tmp/secring.gpg passphrase

...
